# Generated by Django 4.2.1 on 2023-05-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indication',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
