# Generated by Django 4.2.1 on 2023-05-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indication',
            old_name='datetime',
            new_name='end',
        ),
    ]
