# Generated by Django 4.2.1 on 2023-05-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0004_rename_datetime_indication_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indication',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
