# Generated by Django 4.2.1 on 2023-06-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indication',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
