# Generated by Django 4.2.1 on 2023-06-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indication',
            name='height',
        ),
        migrations.RemoveField(
            model_name='indication',
            name='width',
        ),
        migrations.AddField(
            model_name='indication',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mqtt_app.point'),
            preserve_default=False,
        ),
    ]
