# Generated by Django 4.2.1 on 2023-06-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0009_remove_indication_height_remove_indication_width_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='heigth',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='width',
            new_name='longitude',
        ),
    ]
