# Generated by Django 4.2.1 on 2023-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0010_rename_heigth_point_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
