# Generated by Django 4.2.1 on 2024-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0011_indication_status_alter_point_name_alter_sensor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
